question_data = [
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "The Windows ME operating system was released in the year 2000.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "Linux was first created as an alternative to Windows XP.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "Android versions are named in alphabetical order.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
      "correct_answer": "True", "incorrect_answers": ["False"]}
]
